# Lower pitch by one semitone
Ctrl+4 af-command rb multiply-pitch 0.9438743126816935

# Reset pitch to original
Ctrl+5 af-command rb set-pitch 1.0

# Raise pitch by one semitone
Ctrl+6 af-command rb multiply-pitch 1.059463094352953

