# ~/.config/kitty/my_session.conf

# First tab is created by default.

# Create the second tab
new_tab
launch --title admin
cd ~/other/utexas
launch --type=window
launch --type=window

# Create the third tab
new_tab
launch --title msisdir
cd ~/other/utexas/msisdirector/

# Create the fourth tab
new_tab
launch --title hci
cd ~/courses/hci

# Create the fifth tab
new_tab
launch --title appProto
cd ~/courses/appProtoStudio/

# Create the sixth tab
new_tab
launch --title infointeractdsgn
cd ~/courses/infointeractdsgn/

# Create the seventh tab
new_tab
launch --title pdfRemed
cd ~/research/pdfRemediation/

# Create the eighth tab
new_tab
launch --title misc
cd ~/Downloads
launch --type=window
launch --type=window
# launch /opt/homebrew/bin/llama-server -hf unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q4_0 -ngl 99 --jinja --temp 0.0 --port 8999
# launch /opt/homebrew/bin/llama-server -hf unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q4_K_XL -ngl 99 --jinja --temp 0.0 --port 8999
# launch llama-server -m   /Users/mm223266/local-llm-models/Qwen3.6-35B-A3B-Q8_0.gguf --port 8999 -c 4096
# launch llama-server -m   /Users/mm223266/local-llm-models/Qwen3.6-35B-A3B-Q8_0.gguf --port 8999
launch llama-server -m   /Users/mm223266/local-llm-models/Qwen3.6-35B-A3B-Q8_0.gguf -c 70000 -ngl 99 --port 8080

# Create the nineth tab
new_tab
launch --title moremisc
cd ~/Downloads/

